BLUE-1377 Unable to create activation code in TX1 get a blank screen for the activation code
removing the translate directive off the copy to clipboard button to remove the following
directive conflict
Error: [$compile:multidir] Multiple directives [clipCopy, translate] asking for new/isolated scope on:
<button class="btn btn-default btn-lg" clip-copy="genAuthCode.otp.friendlyCode"
clip-click-fallback="genAuthCode.clipboardFallback(copy)"
translate="generateActivationCodeModal.copyToClipboard">